[project]
name = "bigc"
version = "1.0.0"
description = "Unofficial client for the BigCommerce API"
license = "MIT"
license-files = ["LICENSE.txt"]
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Adam Walsh", email = "adam@medshift.com" },
    { name = "Dillon Hartley", email = "dillon@medshift.com" },
    { name = "Milo Weinberg", email = "milo@medshift.com" },
    { name = "Ryan Thomson", email = "ryan@medshift.com" }
]
keywords = ["bigcommerce", "api", "client"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
    "requests~=2.32"
]

[project.urls]
homepage = "https://github.com/MedShift/bigc"
repository = "https://github.com/MedShift/bigc.git"

[dependency-groups]
dev = [
    "pytest~=7.1",
    "ruff==0.16.3",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401",
]

[tool.ruff.format]
line-ending = "lf"
quote-style = "single"
